name: alquran_client
description: A client for alquran.cloud API.
version: 0.0.1
repository: https://github.com/abdushakoor12/alquran_client

environment:
  sdk: ^3.2.6

dependencies:
  equatable: ^2.0.5
  http: ^1.2.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
